allow to lock own artefacts as an editor
spacedeck/spacedeck-open pull request #132
Opened 2020-11-20 18:51 UTC by banglashi

The feature requested was to allow users with the editor's role to lock/unlock their artefacts. A user with an admin role can still unlock them. I hope it makes sense to solve it this way and it has no other implications that I am unaware. Thanks.

2020-11-21 16:12 UTC, mntmn requested changes

2020-11-21 16:12 UTC, mntmn commented on public/javascripts/spacedeck_sections.js
> +      let userArts = true;
nit: please rename to `same_user`, for example, to stay in line with other code style (even if idiosyncratic).

2020-11-21 16:12 UTC, mntmn commented on views/partials/tool/object-options.html
> +    <button class="btn btn-transparent btn-icon-labeled" v-on:click="toggle_lock_of_selected_artifacts()" v-if="active_space_role=='admin' || toolbar_lock_in">
please manually merge latest `mnt` branch changes, there are now `lock_selected_artifacts` and `unlock_selected_artifacts` functions to make the buttons work predictably.

2020-11-23 11:04 UTC, banglashi commented
fixed the 2 comments

2020-11-23 11:10 UTC, merged

2020-11-23 11:10 UTC, mntmn commented
Thanks!