Fixed star and starburst objects so that they render properly within…
spacedeck/spacedeck-open pull request #79
Opened 2020-07-19 18:12 UTC by MishkinBerteig

… the selection bounding box. Lots of math. Still to do is to handle situations when the bounding box is very small and the stroke width of the star[burst] makes the interior corners overlap.  Currently causes weird rendering.  My intention is to check the distance vector of the interior points and if it is less than 1px or negative to instead reduce the stroke width so that the interior points are >= 1px from each other.

NOTE: this fix has no automated tests!  You can [view the results of my work](http://www.mishkinberteig.com/open-source-project-spacedeck/) to check what I have done.

2020-07-22 19:38 UTC, MishkinBerteig commented
@mntmn Please let me know if I need to do anything else to get this pull request accepted.  I noticed that you had code formatting comments for another pull request.  Since this is my first ever pull request, I'm happy to accept any feedback to make it workable!  Thanks in advance, Mishkin.

2020-07-22 19:52 UTC, mntmn requested changes
Hi, thank you and great job! I cannot dissect the maths to check if everything is correct, but judging by your results it looks very good. I just have some typos to fix, please.

2020-07-22 19:52 UTC, mntmn commented on public/javascripts/vector-render.js
> +  //  Fortunately with simple transformations with matricies, we can do rotations and scales easily.
typo: "matrices"

2020-07-22 19:52 UTC, mntmn commented on public/javascripts/vector-render.js
> +  //NOTE: for very think stoke widths, and small stars, the star might render very strangely!
typo: "thin stroke"

2020-07-22 19:52 UTC, mntmn commented on public/javascripts/vector-render.js
> +  } else { //tips == 10
Move the comment to the next line please.

2020-07-23 01:24 UTC, MishkinBerteig commented
@mntmn I _think_ I have correctly committed the updates for this PR.  Please check and let me know if you notice any other problems or if I have to do something different.  Honestly, I don't us git very often (I'm a subversion guy) so it's all a bit new to me.

2020-07-23 23:34 UTC, mntmn approved these changes

2020-07-23 23:35 UTC, merged